/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.ExpensesManagerApi);
    }
}(this, function (expect, ExpensesManagerApi) {
    'use strict';

    var instance;

    beforeEach(function () {
        instance = new ExpensesManagerApi.ExpenseDto();
    });

    var getProperty = function (object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function (object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('ExpenseDto', function () {
        it('should create an instance of ExpenseDto', function () {
            // uncomment below and update the code to test ExpenseDto
            //var instance = new ExpensesManagerApi.ExpenseDto();
            //expect(instance).to.be.a(ExpensesManagerApi.ExpenseDto);
        });

        it('should have the property id (base name: "id")', function () {
            // uncomment below and update the code to test the property id
            //var instance = new ExpensesManagerApi.ExpenseDto();
            //expect(instance).to.be();
        });

        it('should have the property amount (base name: "amount")', function () {
            // uncomment below and update the code to test the property amount
            //var instance = new ExpensesManagerApi.ExpenseDto();
            //expect(instance).to.be();
        });

        it('should have the property description (base name: "description")', function () {
            // uncomment below and update the code to test the property description
            //var instance = new ExpensesManagerApi.ExpenseDto();
            //expect(instance).to.be();
        });

        it('should have the property date (base name: "date")', function () {
            // uncomment below and update the code to test the property date
            //var instance = new ExpensesManagerApi.ExpenseDto();
            //expect(instance).to.be();
        });

        it('should have the property userId (base name: "userId")', function () {
            // uncomment below and update the code to test the property userId
            //var instance = new ExpensesManagerApi.ExpenseDto();
            //expect(instance).to.be();
        });

        it('should have the property categoryId (base name: "categoryId")', function () {
            // uncomment below and update the code to test the property categoryId
            //var instance = new ExpensesManagerApi.ExpenseDto();
            //expect(instance).to.be();
        });

    });

}));
