/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.ExpensesManagerApi);
    }
}(this, function (expect, ExpensesManagerApi) {
    'use strict';

    var instance;

    beforeEach(function () {
        instance = new ExpensesManagerApi.RegistrationDto();
    });

    var getProperty = function (object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function (object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('RegistrationDto', function () {
        it('should create an instance of RegistrationDto', function () {
            // uncomment below and update the code to test RegistrationDto
            //var instance = new ExpensesManagerApi.RegistrationDto();
            //expect(instance).to.be.a(ExpensesManagerApi.RegistrationDto);
        });

        it('should have the property email (base name: "email")', function () {
            // uncomment below and update the code to test the property email
            //var instance = new ExpensesManagerApi.RegistrationDto();
            //expect(instance).to.be();
        });

        it('should have the property password (base name: "password")', function () {
            // uncomment below and update the code to test the property password
            //var instance = new ExpensesManagerApi.RegistrationDto();
            //expect(instance).to.be();
        });

        it('should have the property confirmPassword (base name: "confirmPassword")', function () {
            // uncomment below and update the code to test the property confirmPassword
            //var instance = new ExpensesManagerApi.RegistrationDto();
            //expect(instance).to.be();
        });

    });

}));
