/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.ExpensesManagerApi);
    }
}(this, function (expect, ExpensesManagerApi) {
    'use strict';

    var instance;

    beforeEach(function () {
        instance = new ExpensesManagerApi.UserStatisticsDto();
    });

    var getProperty = function (object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function (object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('UserStatisticsDto', function () {
        it('should create an instance of UserStatisticsDto', function () {
            // uncomment below and update the code to test UserStatisticsDto
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be.a(ExpensesManagerApi.UserStatisticsDto);
        });

        it('should have the property totalIncome (base name: "totalIncome")', function () {
            // uncomment below and update the code to test the property totalIncome
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

        it('should have the property totalExpense (base name: "totalExpense")', function () {
            // uncomment below and update the code to test the property totalExpense
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

        it('should have the property balance (base name: "balance")', function () {
            // uncomment below and update the code to test the property balance
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

        it('should have the property incomePerMonth (base name: "incomePerMonth")', function () {
            // uncomment below and update the code to test the property incomePerMonth
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

        it('should have the property expensePerMonth (base name: "expensePerMonth")', function () {
            // uncomment below and update the code to test the property expensePerMonth
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

        it('should have the property balancePerMonth (base name: "balancePerMonth")', function () {
            // uncomment below and update the code to test the property balancePerMonth
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

        it('should have the property incomePerCategory (base name: "incomePerCategory")', function () {
            // uncomment below and update the code to test the property incomePerCategory
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

        it('should have the property expensePerCategory (base name: "expensePerCategory")', function () {
            // uncomment below and update the code to test the property expensePerCategory
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

        it('should have the property balancePerCategory (base name: "balancePerCategory")', function () {
            // uncomment below and update the code to test the property balancePerCategory
            //var instance = new ExpensesManagerApi.UserStatisticsDto();
            //expect(instance).to.be();
        });

    });

}));
