/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.ExpensesManagerApi);
    }
}(this, function (expect, ExpensesManagerApi) {
    'use strict';

    var instance;

    beforeEach(function () {
        instance = new ExpensesManagerApi.CategoryApi();
    });

    var getProperty = function (object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function (object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('CategoryApi', function () {
        describe('apiCategoryAddOrUpdatePost', function () {
            it('should call apiCategoryAddOrUpdatePost successfully', function (done) {
                //uncomment below and update the code to test apiCategoryAddOrUpdatePost
                //instance.apiCategoryAddOrUpdatePost(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiCategoryDelete', function () {
            it('should call apiCategoryDelete successfully', function (done) {
                //uncomment below and update the code to test apiCategoryDelete
                //instance.apiCategoryDelete(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiCategoryGet', function () {
            it('should call apiCategoryGet successfully', function (done) {
                //uncomment below and update the code to test apiCategoryGet
                //instance.apiCategoryGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiCategoryGetAllGet', function () {
            it('should call apiCategoryGetAllGet successfully', function (done) {
                //uncomment below and update the code to test apiCategoryGetAllGet
                //instance.apiCategoryGetAllGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });

}));
