/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.ExpensesManagerApi);
    }
}(this, function (expect, ExpensesManagerApi) {
    'use strict';

    var instance;

    beforeEach(function () {
        instance = new ExpensesManagerApi.ExpenseApi();
    });

    var getProperty = function (object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function (object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('ExpenseApi', function () {
        describe('apiExpenseAddOrUpdatePost', function () {
            it('should call apiExpenseAddOrUpdatePost successfully', function (done) {
                //uncomment below and update the code to test apiExpenseAddOrUpdatePost
                //instance.apiExpenseAddOrUpdatePost(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiExpenseDelete', function () {
            it('should call apiExpenseDelete successfully', function (done) {
                //uncomment below and update the code to test apiExpenseDelete
                //instance.apiExpenseDelete(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiExpenseGet', function () {
            it('should call apiExpenseGet successfully', function (done) {
                //uncomment below and update the code to test apiExpenseGet
                //instance.apiExpenseGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiExpenseGetAllGet', function () {
            it('should call apiExpenseGetAllGet successfully', function (done) {
                //uncomment below and update the code to test apiExpenseGetAllGet
                //instance.apiExpenseGetAllGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiExpenseGetByAmountRangeGet', function () {
            it('should call apiExpenseGetByAmountRangeGet successfully', function (done) {
                //uncomment below and update the code to test apiExpenseGetByAmountRangeGet
                //instance.apiExpenseGetByAmountRangeGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiExpenseGetByCategoryGet', function () {
            it('should call apiExpenseGetByCategoryGet successfully', function (done) {
                //uncomment below and update the code to test apiExpenseGetByCategoryGet
                //instance.apiExpenseGetByCategoryGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiExpenseGetByDateRangeGet', function () {
            it('should call apiExpenseGetByDateRangeGet successfully', function (done) {
                //uncomment below and update the code to test apiExpenseGetByDateRangeGet
                //instance.apiExpenseGetByDateRangeGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });

}));
