/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.ExpensesManagerApi);
    }
}(this, function (expect, ExpensesManagerApi) {
    'use strict';

    var instance;

    beforeEach(function () {
        instance = new ExpensesManagerApi.IncomeApi();
    });

    var getProperty = function (object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function (object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('IncomeApi', function () {
        describe('apiIncomeAddOrUpdatePost', function () {
            it('should call apiIncomeAddOrUpdatePost successfully', function (done) {
                //uncomment below and update the code to test apiIncomeAddOrUpdatePost
                //instance.apiIncomeAddOrUpdatePost(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiIncomeDelete', function () {
            it('should call apiIncomeDelete successfully', function (done) {
                //uncomment below and update the code to test apiIncomeDelete
                //instance.apiIncomeDelete(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiIncomeDeleteAllDelete', function () {
            it('should call apiIncomeDeleteAllDelete successfully', function (done) {
                //uncomment below and update the code to test apiIncomeDeleteAllDelete
                //instance.apiIncomeDeleteAllDelete(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiIncomeGet', function () {
            it('should call apiIncomeGet successfully', function (done) {
                //uncomment below and update the code to test apiIncomeGet
                //instance.apiIncomeGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiIncomeGetAllGet', function () {
            it('should call apiIncomeGetAllGet successfully', function (done) {
                //uncomment below and update the code to test apiIncomeGetAllGet
                //instance.apiIncomeGetAllGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });

}));
