/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.ExpensesManagerApi);
    }
}(this, function (expect, ExpensesManagerApi) {
    'use strict';

    var instance;

    beforeEach(function () {
        instance = new ExpensesManagerApi.UserApi();
    });

    var getProperty = function (object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function (object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('UserApi', function () {
        describe('apiUserBalanceGet', function () {
            it('should call apiUserBalanceGet successfully', function (done) {
                //uncomment below and update the code to test apiUserBalanceGet
                //instance.apiUserBalanceGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserDeleteAllDelete', function () {
            it('should call apiUserDeleteAllDelete successfully', function (done) {
                //uncomment below and update the code to test apiUserDeleteAllDelete
                //instance.apiUserDeleteAllDelete(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserExportDataGet', function () {
            it('should call apiUserExportDataGet successfully', function (done) {
                //uncomment below and update the code to test apiUserExportDataGet
                //instance.apiUserExportDataGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserFilteredTransactionsGet', function () {
            it('should call apiUserFilteredTransactionsGet successfully', function (done) {
                //uncomment below and update the code to test apiUserFilteredTransactionsGet
                //instance.apiUserFilteredTransactionsGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserGet', function () {
            it('should call apiUserGet successfully', function (done) {
                //uncomment below and update the code to test apiUserGet
                //instance.apiUserGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserImportDataPost', function () {
            it('should call apiUserImportDataPost successfully', function (done) {
                //uncomment below and update the code to test apiUserImportDataPost
                //instance.apiUserImportDataPost(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserStatisticsGet', function () {
            it('should call apiUserStatisticsGet successfully', function (done) {
                //uncomment below and update the code to test apiUserStatisticsGet
                //instance.apiUserStatisticsGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserStatsGraphGet', function () {
            it('should call apiUserStatsGraphGet successfully', function (done) {
                //uncomment below and update the code to test apiUserStatsGraphGet
                //instance.apiUserStatsGraphGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserTotalExpenseGet', function () {
            it('should call apiUserTotalExpenseGet successfully', function (done) {
                //uncomment below and update the code to test apiUserTotalExpenseGet
                //instance.apiUserTotalExpenseGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('apiUserTotalIncomeGet', function () {
            it('should call apiUserTotalIncomeGet successfully', function (done) {
                //uncomment below and update the code to test apiUserTotalIncomeGet
                //instance.apiUserTotalIncomeGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });

}));
