/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class LoginDto {
    static readonly discriminator: string | undefined = undefined;
    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": "password"
        },
        {
            "name": "rememberMe",
            "baseName": "rememberMe",
            "type": "boolean",
            "format": ""
        }];
    'email': string;
    'password': string;
    'rememberMe'?: boolean;

    public constructor() {
    }

    static getAttributeTypeMap() {
        return LoginDto.attributeTypeMap;
    }
}

