/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MemoryStream {
    static readonly discriminator: string | undefined = undefined;
    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "canTimeout",
            "baseName": "canTimeout",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "readTimeout",
            "baseName": "readTimeout",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "writeTimeout",
            "baseName": "writeTimeout",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "canRead",
            "baseName": "canRead",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canSeek",
            "baseName": "canSeek",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canWrite",
            "baseName": "canWrite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "capacity",
            "baseName": "capacity",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": "int64"
        }];
    'canTimeout'?: boolean;
    'readTimeout'?: number;
    'writeTimeout'?: number;
    'canRead'?: boolean;
    'canSeek'?: boolean;
    'canWrite'?: boolean;
    'capacity'?: number;
    'length'?: number;
    'position'?: number;

    public constructor() {
    }

    static getAttributeTypeMap() {
        return MemoryStream.attributeTypeMap;
    }
}

