/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class RegistrationSuccessDto {
    static readonly discriminator: string | undefined = undefined;
    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }];
    'message'?: string | null;

    public constructor() {
    }

    static getAttributeTypeMap() {
        return RegistrationSuccessDto.attributeTypeMap;
    }
}

