/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {AggregatedTotalDto} from '../models/AggregatedTotalDto';

export class UserStatisticsDto {
    static readonly discriminator: string | undefined = undefined;
    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "totalIncome",
            "baseName": "totalIncome",
            "type": "number",
            "format": "double"
        },
        {
            "name": "totalExpense",
            "baseName": "totalExpense",
            "type": "number",
            "format": "double"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number",
            "format": "double"
        },
        {
            "name": "incomePerMonth",
            "baseName": "incomePerMonth",
            "type": "Array<AggregatedTotalDto>",
            "format": ""
        },
        {
            "name": "expensePerMonth",
            "baseName": "expensePerMonth",
            "type": "Array<AggregatedTotalDto>",
            "format": ""
        },
        {
            "name": "balancePerMonth",
            "baseName": "balancePerMonth",
            "type": "Array<AggregatedTotalDto>",
            "format": ""
        },
        {
            "name": "incomePerCategory",
            "baseName": "incomePerCategory",
            "type": "Array<AggregatedTotalDto>",
            "format": ""
        },
        {
            "name": "expensePerCategory",
            "baseName": "expensePerCategory",
            "type": "Array<AggregatedTotalDto>",
            "format": ""
        },
        {
            "name": "balancePerCategory",
            "baseName": "balancePerCategory",
            "type": "Array<AggregatedTotalDto>",
            "format": ""
        }];
    'totalIncome'?: number;
    'totalExpense'?: number;
    'balance'?: number;
    'incomePerMonth'?: Array<AggregatedTotalDto> | null;
    'expensePerMonth'?: Array<AggregatedTotalDto> | null;
    'balancePerMonth'?: Array<AggregatedTotalDto> | null;
    'incomePerCategory'?: Array<AggregatedTotalDto> | null;
    'expensePerCategory'?: Array<AggregatedTotalDto> | null;
    'balancePerCategory'?: Array<AggregatedTotalDto> | null;

    public constructor() {
    }

    static getAttributeTypeMap() {
        return UserStatisticsDto.attributeTypeMap;
    }
}

