/**
 * ExpensesManager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {ExpenseDto} from '../models/ExpenseDto';
import {IncomeDto} from '../models/IncomeDto';

export class UserTransactionsDto {
    static readonly discriminator: string | undefined = undefined;
    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "incomes",
            "baseName": "incomes",
            "type": "Array<IncomeDto>",
            "format": ""
        },
        {
            "name": "expenses",
            "baseName": "expenses",
            "type": "Array<ExpenseDto>",
            "format": ""
        },
        {
            "name": "totalIncome",
            "baseName": "totalIncome",
            "type": "number",
            "format": "double"
        },
        {
            "name": "totalExpense",
            "baseName": "totalExpense",
            "type": "number",
            "format": "double"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number",
            "format": "double"
        }];
    'userId'?: string | null;
    'incomes'?: Array<IncomeDto> | null;
    'expenses'?: Array<ExpenseDto> | null;
    'totalIncome'?: number;
    'totalExpense'?: number;
    'balance'?: number;

    public constructor() {
    }

    static getAttributeTypeMap() {
        return UserTransactionsDto.attributeTypeMap;
    }
}

